
// This file is automatically generated. Do not edit it directly.
import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyAwoJq69A98kXdXUyGpuTMvqUpGyo-gvpQ",
  authDomain: "edgeaura-a0309.firebaseapp.com",
  projectId: "edgeaura-a0309",
  storageBucket: "edgeaura-a0309.firebasestorage.app",
  messagingSenderId: "24760015609",
  appId: "1:24760015609:web:0439084cda89f9f063e028",
  measurementId: "G-WD0LB432B2"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
export const db = getFirestore(app);

